### ISSUE TITLE
启动认证服务和项目管理服务时报错

### ISSUE THREAD

**Issue by cascat0** [laigeoffer/pmhub#31]
认证服务报错如下：
20:40:32.699 [main] WARN  c.a.c.n.c.NacosPropertySourceBuilder - [loadNacosData,87] - Ignore the empty nacos configuration and get it based on dataId[pmhub-auth] & group[DEFAULT_GROUP]
20:40:32.703 [main] WARN  c.a.c.n.c.NacosPropertySourceBuilder - [loadNacosData,87] - Ignore the empty nacos configuration and get it based on dataId[pmhub-auth.yml] & group[DEFAULT_GROUP]
20:40:32.742 [main] INFO  c.l.p.a.PmHubAuthApplication - [logStartupProfileInfo,638] - The following 1 profile is active: "dev"
20:40:34.247 [main] INFO  o.a.c.h.Http11NioProtocol - [log,173] - Initializing ProtocolHandler ["http-nio-6800"]
20:40:34.249 [main] INFO  o.a.c.c.StandardService - [log,173] - Starting service [Tomcat]
20:40:34.249 [main] INFO  o.a.c.c.StandardEngine - [log,173] - Starting Servlet engine: [Apache Tomcat/9.0.83]
20:40:34.482 [main] INFO  o.a.c.c.C.[.[.[/] - [log,173] - Initializing Spring embedded WebApplicationContext
20:40:34.716 [main] WARN  o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext - [refresh,599] - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'loginController': Unsatisfied dependency expressed through field 'tokenService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'com.laigeoffer.pmhub.base.security.service.TokenService': Unsatisfied dependency expressed through field 'redisService'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.laigeoffer.pmhub.base.core.config.redis.RedisService' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
20:40:34.717 [main] INFO  o.a.c.c.StandardService - [log,173] - Stopping service [Tomcat]
20:40:34.771 [main] ERROR o.s.b.d.LoggingFailureAnalysisReporter - [report,40] - 

***************************
APPLICATION FAILED TO START
***************************

Description:

Field redisService in com.laigeoffer.pmhub.base.security.service.TokenService required a bean of type 'com.laigeoffer.pmhub.base.core.config.redis.RedisService' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)

Action:

Consider defining a bean of type 'com.laigeoffer.pmhub.base.core.config.redis.RedisService' in your configuration.

20:40:34.772 [Thread-14] WARN  c.a.n.c.n.NotifyCenter - [shutdown,136] - [NotifyCenter] Start destroying Publisher
20:40:34.772 [Thread-5] WARN  c.a.n.c.h.HttpClientBeanHolder - [shutdown,102] - [HttpClientBeanHolder] Start destroying common HttpClient
20:40:34.773 [Thread-14] WARN  c.a.n.c.n.NotifyCenter - [shutdown,153] - [NotifyCenter] Destruction of the end
20:40:34.773 [Thread-5] WARN  c.a.n.c.h.HttpClientBeanHolder - [shutdown,111] - [HttpClientBeanHolder] Destruction of the end

Process finished with exit code 1

项目管理服务报错如下：
20:57:11.504 [main] WARN  c.a.c.n.c.NacosPropertySourceBuilder - [loadNacosData,87] - Ignore the empty nacos configuration and get it based on dataId[pmhub-project] & group[DEFAULT_GROUP]
20:57:11.509 [main] WARN  c.a.c.n.c.NacosPropertySourceBuilder - [loadNacosData,87] - Ignore the empty nacos configuration and get it based on dataId[pmhub-project.yml] & group[DEFAULT_GROUP]
20:57:11.548 [main] INFO  c.l.p.p.PmHubProjectApplication - [logStartupProfileInfo,638] - The following 1 profile is active: "dev"
20:57:12.660 [main] WARN  o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext - [refresh,599] - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.support.BeanDefinitionOverrideException: Invalid bean definition with name 'logFeignService.FeignClientSpecification' defined in null: Cannot register bean definition [Generic bean: class [org.springframework.cloud.openfeign.FeignClientSpecification]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null] for bean 'logFeignService.FeignClientSpecification': There is already [Generic bean: class [org.springframework.cloud.openfeign.FeignClientSpecification]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null] bound.
20:57:12.687 [main] ERROR o.s.b.d.LoggingFailureAnalysisReporter - [report,40] - 

***************************
APPLICATION FAILED TO START
***************************

Description:

The bean 'logFeignService.FeignClientSpecification' could not be registered. A bean with that name has already been defined and overriding is disabled.

Action:

Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true

20:57:12.688 [Thread-14] WARN  c.a.n.c.n.NotifyCenter - [shutdown,136] - [NotifyCenter] Start destroying Publisher
20:57:12.688 [Thread-5] WARN  c.a.n.c.h.HttpClientBeanHolder - [shutdown,102] - [HttpClientBeanHolder] Start destroying common HttpClient
20:57:12.689 [Thread-14] WARN  c.a.n.c.n.NotifyCenter - [shutdown,153] - [NotifyCenter] Destruction of the end
20:57:12.689 [Thread-5] WARN  c.a.n.c.h.HttpClientBeanHolder - [shutdown,111] - [HttpClientBeanHolder] Destruction of the end

Process finished with exit code 1

**Comment by freestylefly** [comment]
这个是因为没有先启动nacos服务，可以按照教程启动哈：https://laigeoffer.cn/pmhub/quickstart/environment.html
